# Orquestração dos Conteiners - Sobe o banco e o Site juntos
# Para subir os containers: docker compose up -d
# Para parar os containers: docker compose down

services:
  # Serviço do Servidor Web
  web:
    build: .
    container_name: bookshell_app
    ports:
      - "8080:80" # Acessar em localhost:8080
    volumes:
      # Mapeia a pasta atual do Windows para dentro do container
      # Assim, qualquer alteração no código reflete na hora (Hot Reload)
      - .:/var/www/html/BookShell
    depends_on:
      - db
    networks:
      - bookshell-net

  # === Serviço do Banco de Dados ===
  db:
    image: mysql:8.0
    container_name: bookshell_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cadastro_bookshell
    volumes:
      # Persistência de dados (para não perder o banco ao desligar)
      - db_data:/var/lib/mysql
      # Importação Automática: Pega os arquivos SQL e roda na criação do banco
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - bookshell-net

# === PHPMYADMIN ===
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bookshell_pma
    links:
      - db:db
    depends_on:
      - db
    ports:
      - "8081:80" # Acessaremos em localhost:8081
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - bookshell-net

# Definições de rede e volumes
networks:
  bookshell-net:
    driver: bridge

volumes:
  db_data: